# Generated by Django 5.1.6 on 2025-02-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
